DROP DATABASE IF EXISTS JTEST;
CREATE DATABASE JTEST;

USE JTEST;

CREATE TABLE USERS (
	NAME varchar(255) UNIQUE,
	PW varchar(255) NOT NULL,
	ID int NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID)
);

CREATE TABLE CHANNELS(
	ID int NOT NULL AUTO_INCREMENT,
	NAME varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE USERCHANNEL(
	USERID int NOT NULL,
	CHANNELID int NOT NULL,
	FOREIGN KEY (USERID) REFERENCES USERS(ID),
	FOREIGN KEY (CHANNELID) REFERENCES CHANNELS(ID)
);


